spring.application.name=S53_Restful_JPA-1
server.port=8084

spring.datasource.url=jdbc:mysql://localhost:3306/S53emp_db
spring.datasource.username=root
spring.datasource.password=Prasanth@63#7
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect